# Generated by Django 2.2 on 2020-02-12 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тесты',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='TestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='Пройденный тест')),
                ('result', models.IntegerField(blank=True, null=True, verbose_name='Полученный балл')),
                ('modeltest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Test')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История прохождения тестирования пользователями',
                'verbose_name_plural': 'История прохождения тестирования пользователями',
            },
        ),
        migrations.CreateModel(
            name='NameQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Наименование вопроса')),
                ('modeltest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Test')),
            ],
            options={
                'verbose_name': 'Название вопросов',
                'verbose_name_plural': 'Название вопросов',
            },
        ),
        migrations.CreateModel(
            name='AnswerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('result', models.IntegerField(blank=True, null=True, verbose_name='Полученый балл')),
                ('status_answer', models.BooleanField(default=False, verbose_name='Предоставленный ответ')),
                ('modeltestirovanieuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.TestHistory')),
                ('questions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.NameQuestions')),
            ],
            options={
                'verbose_name': 'История ответов пользователей',
                'verbose_name_plural': 'История ответов пользователей',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otvet', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('status', models.BooleanField(blank=True, default=None, verbose_name='Верный ответ')),
                ('questions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.NameQuestions')),
            ],
            options={
                'verbose_name': 'Ответы на вопросы',
                'verbose_name_plural': 'Ответы на вопросы',
            },
        ),
    ]
