# Generated by Django 2.1.5 on 2020-05-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='new2',
            field=models.TextField(blank=True, default=''),
        ),
    ]
