# Generated by Django 2.1.5 on 2020-05-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_text_new2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='New',
        ),
    ]
